/**
 * Codigos de error estandarizados
 */
export const ERROR_CODES = {
  // General
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',

  // Entity
  ENTITY_NOT_FOUND: 'ENTITY_NOT_FOUND',
  ENTITY_DUPLICATED: 'ENTITY_DUPLICATED',
  ENTITY_DELETED: 'ENTITY_DELETED',

  // Database
  DATABASE_ERROR: 'DATABASE_ERROR',
  DATABASE_CONNECTION_ERROR: 'DATABASE_CONNECTION_ERROR',
  DATABASE_CONSTRAINT_ERROR: 'DATABASE_CONSTRAINT_ERROR',

  // Business
  BUSINESS_VALIDATION_ERROR: 'BUSINESS_VALIDATION_ERROR',
  FORBIDDEN_OPERATION: 'FORBIDDEN_OPERATION',

  // Auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
